config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
    :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get '/myprojects' => 'project#list'

  post '/free' => 'charge#free'  
  post '/pay' => 'charge#pay'

  
  get 'admin' => 'admin' #I added this myself. It's from RailsTutorial.org

  root "project#index"

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
  <footer class="page-footer pink darken-2">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Seonaid Lee</h5> <h6 class = "white-text">M.Sc, B.Ed.</h6>
          <p class="grey-text text-lighten-4">Available for complex thought form wrestling. Meditation instruction, technical specifications, and custom word art.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="https://twitter.com/seonaid_lee" target = "_blank">Twitter</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
            <li><a class="grey-text text-lighten-3" href="https://www.linkedin.com/pub/seonaid-lee/95/7b7/33a" target = "_blank">LinkedIn</a></li>
            <li><a class="grey-text text-lighten-3" href="https://instagram.com/seonaid_lee/" target = "_blank">Instagram</a></li>
            <li><%= link_to "Admin", admin_path, :class => "grey-text text-lighten-4" %><li>
          </ul>
        </div>
      </div>
    </div>

    <div class="footer-copyright">
      <div class="container">
      © Seonaid Lee 2015
      <%= link_to "About Me", pages_about_path, :class => "grey-text text-lighten-4 right" %>
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
<header>
    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to "My profile", edit_user_registration_path %></li>
      <li><%= link_to "My Projects", myprojects_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>

    <ul id="dropdown2" class="dropdown-content">
      <li><%= link_to "My profile", edit_user_registration_path %></li>
      <li><%= link_to "My Projects", myprojects_path %></li>
      <li class="divider"></li>
      <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    </ul>

    <nav class="pink darken-2 z-depth-1">
      <div class="container">
      <div class="nav-wrapper">

        <%= link_to "Seonaid Lee", root_path, :class => "brand-logo" %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "All Projects", root_path %></li>
          <% if (!user_signed_in?) %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
            <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
              <%= image_tag avatar_url(current_user), class: "circle avatar-small"%> &nbsp;
              <%= current_user.name %>
              <i class="mdi-navigation-arrow-drop-down right"></i></a></li>
          <% end %>
       </ul>

        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to "All Projects", root_path %></li>
           <% if (!user_signed_in?) %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
            <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-small" %> &nbsp;
              <%= current_user.name %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
          <% end %>
        </ul>
      </div>
    </div>
    </nav>
  </header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type = "text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
				toastr['<%= type %>']('<%= f[1] %> ')
		<% end %>
	</script>
<% end %>