config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
    :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get '/myprojects' => 'project#list'

  post '/free' => 'charge#free'  
  post '/pay' => 'charge#pay'

  
  get 'admin' => 'admin' #I added this myself. It's from RailsTutorial.org

  root "project#index"

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  
  has_many :tasks
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :reviews

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { only_integer: true }

  has_attached_file :image, :styles => { :medium => "680x300", :thumb => "170x75" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def average_rating
    reviews.blank? ? 0: reviews.average(:star).round(2)
  end

  def price_in_cents
    price*100
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!, only: [:list]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(:tag)

    @joined = false

    if !current_user.nil? && !current_user.projects.nil?
      @joined = current_user.projects.include?(@project)
    end

    @users = @project.users.order('created_at desc').first(10)

    @review = Review.new
    @reviews = @project.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def list
    if !current_user.nil?
      @projects = current_user.projects
    end
  end

end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/index.html.erb
<h1>Projects</h1>

  <div class="row">
    <% @projects.each do |project| %>       
      <div class="col s12 m6 l4">
        <%= link_to project do %>
          <div class="card ">
            <div class="card-image">
              <%= image_tag project.image %>
              <span class="card-title"><%= project.name %></span>
            </div>
            <div class="card-content">
              <p><%= truncate(project.content, :length => 50 )%> </p>
            </div>
            <div class="card-action pink darken-3">
              See Details
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/project/list.html.erb
<h1>In Progress</h1>

  <div class="row">
    <% if @projects.count > 0 %>
      <% @projects.each do |project| %>       
        <div class="col s12 m6 l4">
          <%= link_to project do %>
            <div class="card ">
              <div class="card-image">
                <%= image_tag project.image %>
                <span class="card-title"><%= project.name %></span>
              </div>
              <div class="card-content">
                <p><%= truncate(project.content, :length => 50 )%> </p>
              </div>
              <div class="card-action pink darken-3">
                See Details
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="center">
        <div>You are not currently enrolled in any projects. </div>
        <%= link_to "Show me all projects", root_path,:class => "btn" %>
      </div>
    <% end %>
  </div>

app/views/project/show.html.erb
<% content_for :head do %>
  <title><%= @project.name %> | WhereAmI  </title>

<!-- Twitter card data -->
  <meta name = "twitter:card" content="summary_large_image">
  <meta name = "twitter:site" content="@seonaid_lee">
  <meta name = "twitter:creator" content="@seonaid_lee">
  <meta name = "twitter:title" content="<%= @project.name %>">
  <meta name = "twitter:description" content="<%= @project.content %>">
  <meta name = "twitter:image:src" content="<%= image_url @project.image %>">

<!-- Open Graph data -->
  <meta property = "og:site_name" content="Seonaid Lee">
  <meta property = "og:type" content="website">
  <meta property = "og:title" content="<%= @project.name %>">
  <meta property = "og:description" content="<%= @project.content %>">
  <meta property = "og:image" content="<%= @project.image %>">

<% end %>
<div class="row">
  <div class="col m4 ">
    <div class="card ">

      <% if !@joined %>
       <div class="center ">
          <h2> <%= @project.price == 0? "Free": "$#{@project.price}" %> </h2>
          <div class = "card-action" >
            <% if user_signed_in? %>
              <% if @project.price == 0 %>
                <%= form_tag free_path do %>
                  <%= hidden_field_tag 'project_id', @project.id %>
                  <button type = "submit" class = "btn"> Take this Project </button>
                <% end %>
              <% else %>
                <%= form_tag pay_path, id:'chargeForm' do %>
                  <script src="https://checkout.stripe.com/checkout.js"></script>
                  <%= hidden_field_tag 'stripeToken' %>
                  <%= hidden_field_tag 'stripeEmail' %>
                  <%= hidden_field_tag 'project_id', @project.id %>

                  <button id="purchaseButton" type = "button" class = "btn">Buy Now</button>
                  <br/>

                  <script>
                    var handler = StripeCheckout.configure({
                      key: '<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>',
                      token: function(token) {
                        $('#stripeToken').val(token.id);
                        $('#stripeEmail').val(token.email);
                        $('#chargeForm').submit();
                      }
                    });

                    $('#purchaseButton').on('click', function(e) {
                      handler.open({
                        name: 'PracticalSchmactical',
                        description: '<%= @project.name %>',
                        amount: '<%= @project.price_in_cents %>',
                        email: '<%= current_user.email %>'
                      });
                      e.preventDefault();
                    });

                  </script>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to "Buy Now", new_user_session_path, :class => "btn center" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="center ">
          <%=image_tag avatar_url(current_user), :class => "circle responsive-img avatar-medium" %> 
          <br /> <h5> <%= current_user.name %> </h5>
          <div class = "card-action center" >
            <h5 class = "black-text">Enrolled in project </h5>
              <ul class = "collection">
              <% @users.each do |u| %>
                <li class = "valign-wrapper black-text collection-item">
                  <%=image_tag avatar_url(u), :class => "circle responsive-img avatar-small" %> &nbsp;
                  <%= u.name %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

    </div>    
  </div>

  <div class="col m8">
    <div class="card ">
      <div class="card-image"><%= image_tag @project.image %>
        <span class="card-title"><%= @project.name %></span>
      </div>

<!-- Navigation tabs -->
      <div class="row">
        <div class="col s12">
          <ul class="tabs">
            <li class="tab col s3"><a class="active" href="#about">About</a></li>
            <li class="tab col s3"><a href="#videos">Videos</a></li>
            <li class="tab col s3"><a href="#discussion">Discussion</a></li>
          </ul>
        </div>
        <div id="about" class="col s12">
          <div class="card-content">
            <div><span id = "average_rating"></span>
              <%= @reviews.count %> <%= @reviews.count > 1? "Reviews" : "Review" %> </div>
            <%= @project.content %>
            <h4>Reviews</h4>
            <div><%= render 'reviews/form' if @joined && !@hasReview %></div>
            <div><%= render 'reviews/index' %></div>

          </div>
        </div>
        
        <div id="videos" class="col m12">
          <div class="card-content">
            <div class="collection with-header">
              <% @tasks.each do |task| %>
                <% if task.header %>
                  <div class="collection-header">
                    <%= task.title %> >
                  </div>
                <% else %>
                  <%= link_to [task.project, task], :class => "collection-item" do %>
                    <%= task.title %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>

        </div>
        
        <div id="discussion" class="col s12">
          <div class="card-content">
            <div id="disqus_thread"></div>
              <script type="text/javascript">
                  /* * * CONFIGURATION VARIABLES * * */
                  var disqus_shortname = 'seonaidlee';
                  var disqus_identifier = '<%= @project.id %>';
                  
                  /* * * DON'T EDIT BELOW THIS LINE * * */
                  (function() {
                      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                  })();
              </script>
              <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @project.average_rating %>,
  });
</script>